### auth
// @no-cookie-jar
// @no-log
GET http://localhost/bitrix/admin/1c_exchange.php?type=sale&mode=checkauth
Authorization: Basic 1cobmen 1cobmenPassword

> {%
// client.log(JSON.stringify(response));

var rows = response.body.split(/\n/);
client.test('Авторизация', function(){
    client.assert(rows[0] === 'success', "Авторизация не прошла");
});

if(rows[0] === 'success')
{
    client.global.set("1C_REQUEST_COOKIE_PHP_SESSID", rows[2]);
    client.global.set("1C_REQUEST_SESSID_VARIABLE", rows[3].split('=').pop());
}
%}

### init
// @no-log
GET http://localhost/bitrix/admin/1c_exchange.php?type=sale&mode=init&sessid={{1C_REQUEST_SESSID_VARIABLE}}&version=3.1
Cookie: PHPSESSID={{1C_REQUEST_COOKIE_PHP_SESSID}}


### query
GET http://localhost/bitrix/admin/1c_exchange.php?type=sale&mode=query&sessid={{1C_REQUEST_SESSID_VARIABLE}}&version=3.1
Cookie: PHPSESSID={{1C_REQUEST_COOKIE_PHP_SESSID}}

<> 2023-06-14T175532.200.xml


